import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import ts from 'typescript';
import {managementFixture,id} from './management-fixture.mjs';
const require=createRequire(import.meta.url);
function load(path,mocks={},globals={}){const js=ts.transpileModule(readFileSync(new URL('../'+path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;const module={exports:{}};vm.runInNewContext(`(function(require,module,exports){${js}\n})`,{console,process,Date,crypto:globalThis.crypto,setTimeout,clearTimeout,...globals})(n=>n in mocks?mocks[n]:n==='server-only'?{}:require(n),module,module.exports);return module.exports;}
const model=load('lib/management/model.ts');
for(const [q,low,critical,want] of [[null,null,null,'Count needed'],[-2,null,null,'Reconcile'],[1,null,null,'Unconfigured'],[750,2250,750,'Critical'],[1000,2250,750,'Low'],[3000,2250,750,'Healthy']])test('stock status '+want,()=>assert.equal(model.stockStatus(q,low,critical),want));
test('category and status filters do not infer configuration',()=>{assert.equal(model.filteredInventory(managementFixture().inventory,'','BEER','Reconcile').length,1);assert.equal(model.filteredInventory(managementFixture().inventory,'lime','All','Low').length,0);});
for(const [q,f,quantum,want] of [['2','24','1','48'],['6','750','1','4500'],['10.5','750','1','7875.0'],['0.1','1','1e-9','0.1']])test('exact package conversion '+q+' × '+f,()=>assert.equal(model.normalizeQuantity(q,f,quantum),want));
test('invalid/indivisible quantities rejected',()=>{for(const args of [['0.1','1','1'],['1','0','1'],['1000000000000','1','1'],['NaN','1','1']])assert.throws(()=>model.normalizeQuantity(...args));});
test('commands reject browser actor, direct quantities and invalid roles',()=>{const base={kind:'receive',id:id(1),key:id(2),quantity:'2',unit:'case'};assert.equal(model.parseCommand(base).kind,'receive');for(const extra of [{actor:id(3)},{base_quantity:99},{quantity:'-1'},{quantity:'NaN'},{unit:''}])assert.throws(()=>model.parseCommand({...base,...extra}));assert.throws(()=>model.parseCommand({kind:'staff',id:id(1),key:id(2),role:'owner'}));});
const {NextRequest}=require('next/server');
const environment=load('lib/bartender/environment.ts'),access=load('lib/auth/access.ts');
function route(role='management',env={NEXT_PUBLIC_SUPABASE_URL:'https://mfwoutniamoldcieoqvc.supabase.co',VERCEL_ENV:'preview'},apply=async()=>({})){let writes=0;return {get writes(){return writes;},api:load('app/api/management/operations/route.ts',{'@/lib/supabase/server':{createClient:async()=>({})},'@/lib/auth/access':{...access,resolveAccess:async()=>role==='anonymous'?{kind:'anonymous'}:role==='inactive'?{kind:'blocked'}:{kind:'staff',staff:{role}}},'@/lib/bartender/environment':environment,'@/lib/management/model':model,'@/lib/management/service':{loadManagement:async()=>managementFixture(),applyManagement:async(...args)=>{writes++;return apply(...args);}}},{process:{env}})};}
const req=body=>new NextRequest('https://local.invalid/api/management/operations',{method:'POST',headers:{origin:'https://local.invalid'},body:JSON.stringify(body)});
for(const role of ['bartender','inactive','anonymous'])test('Management API denies '+role,async()=>{const r=route(role);assert.equal((await r.api.GET()).status,403);assert.equal((await r.api.POST(req({kind:'cancel',id:id(1),key:id(2)}))).status,403);assert.equal(r.writes,0);});
test('Production and wrong project deny operations',async()=>{for(const env of [{VERCEL_ENV:'production',NEXT_PUBLIC_SUPABASE_URL:'https://mfwoutniamoldcieoqvc.supabase.co'},{VERCEL_ENV:'preview',NEXT_PUBLIC_SUPABASE_URL:'https://wrong.supabase.co'}])assert.equal((await route('management',env).api.GET()).status,403);});
test('Management route enforces session and keeps demo gated',()=>{assert.match(readFileSync('app/management/layout.tsx','utf8'),/requireStaff\("management"\)/);assert.match(readFileSync('app/management/page.tsx','utf8'),/demoEnabled\(process.env\)&&<SalesDemo/);});
test('API distinguishes stale revision, rejection and unknown outcome',async()=>{for(const [error,status] of [[{code:'P0001',conflict:true},'conflict'],[{code:'P0001'},'failed'],[{},'uncertain']]){const r=route('management',undefined,async()=>{throw error;});const b=await (await r.api.POST(req({kind:'count',id:id(1),key:id(2),quantity:'1',unit:'ml',revision:1}))).json();assert.equal(b.status,status);}});
test('API rejects foreign origin before writes',async()=>{const r=route();assert.equal((await r.api.POST(new NextRequest('https://local.invalid/api/management/operations',{method:'POST',headers:{origin:'https://evil.invalid'}}))).status,403);assert.equal(r.writes,0);});
test('receiving normalizes on server and counts preserve revision/key',async()=>{
 const calls=[];const tables={inventory_accounts:{id:id(1),item_id:id(2)},inventory_items:{base_unit:'unit',quantum:1,active:true},inventory_unit_conversions:{base_quantity:24}};
 const c={from:t=>{const q={select:()=>q,eq:()=>q,single:async()=>({data:tables[t]})};return q;},rpc:async(n,p)=>{calls.push({n,p});return {data:{}};}};
 const s=load('lib/management/service.ts',{'./model':model});
 await s.applyManagement(c,{kind:'receive',id:id(1),key:id(9),quantity:'2',unit:'case'});assert.equal(calls[0].n,'adjust_inventory');assert.equal(calls[0].p.p_delta,'48');assert.equal(calls[0].p.p_reason,'Receipt');
 await s.applyManagement(c,{kind:'count',id:id(1),key:id(10),quantity:'3',unit:'case',revision:5});assert.equal(calls[1].p.p_count,'72');assert.equal(calls[1].p.p_revision,5);assert.equal(calls[1].p.p_operation_key,id(10));
 tables.inventory_accounts.item_id=null;await assert.rejects(s.applyManagement(c,{kind:'receive',id:id(1),key:id(9),quantity:'1',unit:'batch'}));assert.equal(calls.length,2);
});

test('Management UI: read views, receiving, bulk partial conflict, safe retry, prep and staff',async()=>{
 const {JSDOM}=await import('jsdom');const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost/'});const previous={window:globalThis.window,document:globalThis.document};globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.IS_REACT_ACT_ENVIRONMENT=true;
 const React=require('react'),{act}=React,{createRoot}=require('react-dom/client'),root=createRoot(document.getElementById('root'));const snapshot=managementFixture(),writes=[];let countConflict=true,uncertain=false;dom.window.confirm=()=>true;
 const fetch=async(url,o={})=>{if(!o.method)return {ok:true,json:async()=>structuredClone(snapshot)};const c=JSON.parse(o.body);writes.push(c);if(uncertain){uncertain=false;throw new Error('network');}if(c.kind==='count'&&c.id===id(2)&&countConflict){countConflict=false;snapshot.inventory[1].revision=5;return {ok:false,status:409,json:async()=>({status:'conflict',message:'Stock changed'})};}return {ok:true,json:async()=>({status:'applied'})};};
 const styles=new Proxy({},{get:(_,k)=>String(k)});const C=load('app/management/workspace.tsx',{'@/lib/management/model':model,'./workspace.module.css':{__esModule:true,default:styles}},{fetch,window:dom.window,sessionStorage:dom.window.sessionStorage,AbortSignal}).default;
 const click=async(text)=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent===text);assert.ok(b,text);assert.ok(!b.disabled,text+' enabled');await act(async()=>b.click());};
 const input=async(label,value)=>{const el=[...document.querySelectorAll('input,select')].find(e=>e.getAttribute('aria-label')===label||e.closest('label')?.textContent.startsWith(label));assert.ok(el,label);await act(async()=>{const proto=el.tagName==='SELECT'?dom.window.HTMLSelectElement.prototype:dom.window.HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(el,value);el.dispatchEvent(new dom.window.Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));});};
 const capture=name=>{mkdirSync('/tmp/bar-tools-management-review',{recursive:true});const css=readFileSync('app/management/workspace.module.css','utf8');writeFileSync('/tmp/bar-tools-management-review/'+name+'.html','<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Management local synthetic review</title><style>body{margin:0;background:#f5f7f3;color:#25372d;font:16px system-ui}button{padding:10px 14px;background:#168a7f;border:0;border-radius:6px;color:white;cursor:pointer}button.secondary{background:white;color:#26332f;border:1px solid #afc8bc}h2{font-size:1.2rem}p{line-height:1.5}'+css+'</style><p>LOCAL SYNTHETIC REVIEW — no backend connection</p>'+document.getElementById('root').innerHTML);};
 try{
 await act(async()=>root.render(React.createElement(C,{staffId:id(50),initial:snapshot,signOut:null,demo:React.createElement('p',{},'Preview demo retained')})));
 assert.match(document.body.textContent,/Needs attention/);assert.match(document.body.textContent,/-2 unit/);capture('overview');
 await click('Inventory');capture('inventory');await input('Category','BEER');assert.equal(document.querySelectorAll('tbody tr').length,1);await input('Category','All');
 await click('Receive');await input('Quantity','6');await act(async()=>document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));assert.equal(writes.at(-1).kind,'receive');assert.equal(writes.at(-1).unit,'bottle');
 await click('Physical count');await input('Count '+snapshot.inventory[0].name,'1');await input('Count Corona','8');capture('counts');await click('Reconcile entered counts');assert.equal(writes.filter(w=>w.kind==='count').length,2);assert.match(document.body.textContent,/conflict/);
 await click('Reconcile entered counts');assert.equal(writes.filter(w=>w.kind==='count').length,2,'applied/conflicted rows never automatically resent');
 await click('Review and re-enter');await input('Count Corona','8');await click('Reconcile entered counts');assert.equal(writes.at(-1).revision,5);assert.equal(writes.filter(w=>w.kind==='count'&&w.id===id(1)).length,1);
 await click('Prep');capture('prep');await click('Edit threshold');await input('Standardized batches','0.5');await act(async()=>document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));assert.equal(writes.at(-1).kind,'threshold');
 await click('Cancel request');assert.equal(writes.at(-1).kind,'cancel');snapshot.requests=[];await click('Update view');await click('Request prep');await input('Standardized batches','2');await input('Note (optional)','Happy hour');await act(async()=>document.querySelector('form').dispatchEvent(new dom.window.Event('submit',{bubbles:true,cancelable:true})));assert.equal(writes.at(-1).note,'Happy hour');
 await click('Recipes');assert.match(document.body.textContent,/Combine/);assert.match(document.body.textContent,/read-only/);capture('recipes');
 await click('Staff');capture('staff');uncertain=true;await click('Deactivate');const saved={...writes.at(-1)};assert.match(document.body.textContent,/unconfirmed/);await click('Retry same action');assert.deepEqual(writes.at(-1),saved);await click('Make bartender');assert.equal(writes.at(-1).role,'bartender');
 }finally{await act(async()=>root.unmount());dom.window.close();Object.assign(globalThis,previous);delete globalThis.IS_REACT_ACT_ENVIRONMENT;}
});
