import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import ts from 'typescript';
import {randomUUID} from 'node:crypto';
const require=createRequire(import.meta.url);
function load(path,mocks={},globals={}){const js=ts.transpileModule(readFileSync(new URL('../'+path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;const module={exports:{}};vm.runInNewContext(`(function(require,module,exports){${js}\n})`,{console,process,Date,crypto:globalThis.crypto,setTimeout,clearTimeout,...globals})(n=>n in mocks?mocks[n]:n==='server-only'?{}:require(n),module,module.exports);return module.exports;}
const fixtures=JSON.parse(readFileSync(new URL('../lib/sales-demo/fixtures.json',import.meta.url)));
const config=load('lib/sales-demo/config.ts',{'./fixtures.json':fixtures});
const execution=()=>`${Date.now()}:${randomUUID()}`;
const preview={VERCEL_ENV:'preview',SALES_DEMO_ENABLED:'1',NEXT_PUBLIC_SUPABASE_URL:'https://mfwoutniamoldcieoqvc.supabase.co'};
for(const [name,env,expected] of [['preview',preview,true],['production',{...preview,VERCEL_ENV:'production'},false],['wrong project',{...preview,NEXT_PUBLIC_SUPABASE_URL:'https://other.supabase.co'},false],['disabled',{...preview,SALES_DEMO_ENABLED:'0'},false],['local',{...preview,VERCEL_ENV:undefined,NODE_ENV:'development',NEXT_PUBLIC_SUPABASE_URL:'http://127.0.0.1:54321'},true],['local production build',{...preview,VERCEL_ENV:undefined,NODE_ENV:'production'},false]])test(`demo gate ${name}`,()=>assert.equal(config.demoEnabled(env),expected));
test('20 fixed sales have stable retry contract and all categories',()=>{const e=execution();assert.equal(config.sequence.length,20);const sales=config.sequence.map((_,i)=>config.saleFor(e,i,['a','b','c','d','e']));assert.equal(new Set(sales.map(s=>s.menu_item_id)).size,5);assert.equal(new Set(sales.map(s=>s.sale_id)).size,20);assert.deepEqual(config.saleFor(e,0,['a']),config.saleFor(e,0,['a']));assert.throws(()=>config.saleFor(e,20,[]));});
const {NextRequest}=require('next/server');
function route(role='management',env=preview){let calls=[];const mod=load('app/api/management/demo/route.ts',{'@/lib/supabase/server':{createClient:async()=>({})},'@/lib/auth/access':{resolveAccess:async()=>role==='inactive'?{kind:'blocked'}:{kind:'staff',staff:{role}}},'@/lib/sales-demo/config':config,'@/lib/sales-demo/service':{demoState:async()=>({ready:true}),ingestDemo:async(...args)=>{calls.push(args);return {quantity:2};},resetDemo:async()=>({ready:true})}},{process:{env}});return {mod,calls};}
for(const role of ['bartender','inactive','anonymous'])test(`route denies ${role}`,async()=>assert.equal((await route(role).mod.GET()).status,403));
for(const env of [{...preview,VERCEL_ENV:'production'},{...preview,NEXT_PUBLIC_SUPABASE_URL:'https://wrong.supabase.co'}])test('route rejects forbidden environment before sales',async()=>{const r=route('management',env);assert.equal((await r.mod.POST(new NextRequest('https://app.invalid/api/management/demo',{method:'POST',headers:{origin:'https://app.invalid'},body:JSON.stringify({execution:execution(),index:0})}))).status,403);assert.equal(r.calls.length,0);});
test('route permits management, denies arbitrary injection and foreign origin',async()=>{const r=route();const send=(body,origin='https://app.invalid')=>r.mod.POST(new NextRequest('https://app.invalid/api/management/demo',{method:'POST',headers:{origin},body:JSON.stringify(body)}));assert.equal((await send({execution:execution(),index:0})).status,200);for(const extra of ['menu_item_id','quantity','account_id','ingredient_id'])assert.equal((await send({execution:execution(),index:0,[extra]:'bad'})).status,400);assert.equal((await send({execution:execution(),index:0},'https://evil.invalid')).status,403);assert.equal(r.calls.length,1);});
function database(){
 const d={inventory_items:fixtures.raw.map(x=>({id:x.key,name:fixtures.prefix+x.name,active:true,base_unit:x.unit,quantum:x.quantum})),recipes:[{id:'recipe',name:fixtures.prefix+fixtures.recipe.name,active:true}],recipe_versions:[{id:'version',recipe_id:'recipe',approved_at:'yes',production_mode:'SIMPLE',production_increment:0.5,stock_identity_id:'stock'}],recipe_requirements:fixtures.recipe.ingredients.map(x=>({recipe_version_id:'version',item_id:x.key,quantity_per_batch:x.quantity})),batch_stock_identities:[{id:'stock',recipe_id:'recipe',standard_qty:1,standard_unit:'L'}],recipe_operational_settings:[{recipe_id:'recipe',prep_threshold:0.3}],inventory_accounts:[...fixtures.raw.map(x=>({id:x.key+'-ac',item_id:x.key})),{id:'batch-ac',stock_identity_id:'stock'}],inventory_balances:[...fixtures.raw.map(x=>({account_id:x.key+'-ac',quantity:x.baseline,revision:1,initialized:true})),{account_id:'batch-ac',quantity:1,revision:1,initialized:true}],menu_items:fixtures.menu.map((x,i)=>({id:'m'+i,name:fixtures.prefix+x.name,active:true})),serving_definitions:fixtures.menu.map((_,i)=>({id:'d'+i,menu_item_id:'m'+i,approved_at:'yes'})),serving_requirements:fixtures.menu.flatMap((m,i)=>m.requirements.map(r=>({serving_definition_id:'d'+i,item_id:r.key==='batch'?null:r.key,stock_identity_id:r.key==='batch'?'stock':null,quantity_per_serving:r.quantity}))),batch_runs:[],batch_requests:[]};
 const c={from:t=>({select:()=>({in:(column,ids)=>({limit:()=>Promise.resolve({data:d[t].filter(r=>ids.includes(r[column])),error:null})})})})};return {d,c};
}
function service(db,failAt=Infinity){const calls=[];const s=load('lib/sales-demo/service.ts',{'./config':config,'@/lib/bartender/service':{rpc:async(c,name,p)=>{calls.push({name,p});if(calls.length===failAt)throw new Error('network');if(name==='ingest_sale')return {status:'APPLIED'};const b=db.d.inventory_balances.find(b=>b.account_id===p.p_account);assert.equal(p.p_revision,b.revision);b.quantity=p.p_count;b.revision++;return {};}}});return {s,calls};}
test('dedicated reset restores deficits and never touches unrelated accounts',async()=>{const db=database();db.d.inventory_balances[0].quantity=-10;db.d.inventory_balances.at(-1).quantity=-1;db.d.inventory_balances.push({account_id:'other',quantity:99});const {s,calls}=service(db);await s.resetDemo(db.c);assert.equal(calls.length,2);assert.ok(calls.every(x=>x.name==='record_inventory_count'));assert.equal(db.d.inventory_balances.at(-1).quantity,99);assert.equal((await s.demoState(db.c)).ready,true);});
test('partial reset remains unready and a later reset finishes baseline',async()=>{const db=database();db.d.inventory_balances[0].quantity=-10;db.d.inventory_balances[1].quantity=0;const {s}=service(db,2);await assert.rejects(s.resetDemo(db.c));assert.equal((await s.demoState(db.c)).ready,false);await service(db).s.resetDemo(db.c);assert.equal((await s.demoState(db.c)).ready,true);});
test('reset refuses active production and foreign serving input',async()=>{const db=database();db.d.batch_runs.push({recipe_version_id:'version',lifecycle:'IN_PROGRESS'});const {s,calls}=service(db);await assert.rejects(s.resetDemo(db.c));assert.equal(calls.length,0);db.d.batch_runs=[];db.d.serving_requirements[0].stock_identity_id='foreign';await assert.rejects(s.resetDemo(db.c));assert.equal(calls.length,0);});
test('negative stock still yields successful real ingestion, never a request',async()=>{const db=database();db.d.inventory_balances.at(-1).quantity=-1;const {s,calls}=service(db);const e=execution();assert.equal((await s.ingestDemo(db.c,e,0)).quantity,2);await s.ingestDemo(db.c,e,0);assert.equal(calls[0].name,'ingest_sale');assert.deepEqual(calls[0].p,calls[1].p);assert.ok(calls.every(x=>x.name==='ingest_sale'));});
const controller=load('lib/sales-demo/controller.ts',{'./config':config});
test('fixed day schedules twenty serial sales and retains only latest five',async()=>{
 let next=null,state;const indices=[];
 const c=controller.createDemoController(async(m,p)=>{if(m==='GET')return {ready:true};indices.push(p.index);return {saleId:String(p.index)};},s=>state=s,fn=>{next=fn;return 1;},()=>{next=null;});
 await c.check();c.start();
 for(let i=0;i<20;i++){
  await new Promise(r=>setImmediate(r));
  if(i<19){assert.equal(typeof next,'function');const fn=next;next=null;fn();}
 }
 assert.deepEqual(indices,Array.from({length:20},(_,i)=>i));
 assert.equal(state.running,false);assert.equal(state.pending,false);assert.equal(next,null);
 assert.deepEqual(Array.from(state.feed,s=>s.saleId),['19','18','17','16','15']);c.dispose();
});
test('Start/Stop waits for one in-flight sale; disposal cancels scheduling',async()=>{let next,state,finish;const methods=[];const c=controller.createDemoController(async m=>{methods.push(m);if(m==='GET')return {ready:true};return new Promise(r=>finish=r);},s=>state=s,fn=>{next=fn;return 1;},()=>{next=null;});await c.check();c.start();c.start();assert.equal(methods.filter(m=>m==='POST').length,1);c.stop();finish({saleId:'one'});await new Promise(r=>setImmediate(r));assert.equal(state.pending,false);assert.equal(next,null);c.dispose();});
test('technical failure retains exact sale retry and blocks reset/restart',async()=>{let state,payloads=[],saved=null;const c=controller.createDemoController(async(m,p)=>{if(m==='GET')return {ready:true};payloads.push(p);if(payloads.length===1)throw new Error('network');return {saleId:'same'};},s=>state=s,setTimeout,clearTimeout,{read:()=>saved,write:p=>saved=p});await c.check();c.start();await new Promise(r=>setImmediate(r));assert.equal(state.uncertain,true);assert.match(state.message,/Technical error/);await c.reset();c.start();assert.equal(payloads.length,1);await c.retry();assert.deepEqual(payloads[0],payloads[1]);assert.equal(saved,null);c.dispose();});
test('partial reset blocks Start until restored, and saved unknown sale survives reload',async()=>{let state,fail=true;const c=controller.createDemoController(async m=>{if(m==='DELETE'&&fail)throw new Error();return {ready:true};},s=>state=s);await c.check();await c.reset();assert.equal(state.ready,false);assert.match(state.message,/Reset incomplete/);fail=false;await c.reset();assert.equal(state.ready,true);c.dispose();const other=controller.createDemoController(async()=>({ready:true}),s=>state=s,setTimeout,clearTimeout,{read:()=>({execution:execution(),index:2}),write:()=>{}});await other.check();assert.equal(state.uncertain,true);assert.equal(state.ready,false);other.dispose();});
test('panel offers only minimal controls and five-row management feed; gating is server-side',()=>{const source=readFileSync(new URL('../app/management/page.tsx',import.meta.url),'utf8');assert.match(source,/requireStaff\("management"\)/);assert.match(source,/demoEnabled\(process.env\)&&<SalesDemo/);const ui=readFileSync(new URL('../app/management/sales-demo.tsx',import.meta.url),'utf8');for(const label of ['Start simulated day','Stop','Reset demo','Retry same sale'])assert.ok(ui.includes(label));assert.ok(!readFileSync(new URL('../app/bartender/workspace.tsx',import.meta.url),'utf8').includes('SalesDemo'));});
