'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {categories,filteredInventory,displayQuantity,type Snapshot,type Inventory,type Command} from '@/lib/management/model';
import styles from './workspace.module.css';
type Section='Overview'|'Inventory'|'Prep'|'Recipes'|'Activity'|'Staff';
type RowResult={status:'applied'|'conflict'|'failed'|'uncertain';message?:string};
const fmt=(n:number|null)=>n===null?'Not counted':new Intl.NumberFormat('en',{maximumFractionDigits:3}).format(n);
const key=()=>crypto.randomUUID();
export default function ManagementWorkspace({staffId,demo,signOut,initial}:{staffId:string;demo:ReactNode;signOut:ReactNode;initial?:Snapshot}){
 const [data,setData]=useState<Snapshot|null>(initial??null),[section,setSection]=useState<Section>('Overview'),[quickSearch,setQuickSearch]=useState(''),[element,setElement]=useState<string|null>(null),[search,setSearch]=useState(''),[category,setCategory]=useState('All'),[status,setStatus]=useState('All');
 const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<Command|null>(null);const lock=useRef(false);
 const [receive,setReceive]=useState<string|null>(null),[qty,setQty]=useState(''),[unit,setUnit]=useState(''),[countMode,setCountMode]=useState(false);
 const [counts,setCounts]=useState<Record<string,{value:string;unit:string;revision:number}>>({}),[results,setResults]=useState<Record<string,RowResult>>({});
 const [prepForm,setPrepForm]=useState<{id:string;kind:'request'|'threshold'}|null>(null),[prepQty,setPrepQty]=useState(''),[note,setNote]=useState('');
 const redirect=(body:{redirect?:string})=>{if(body.redirect)window.location.assign(body.redirect);};
 const load=async()=>{try{const r=await fetch('/api/management/operations',{cache:'no-store'});const b=await r.json();redirect(b);if(!r.ok)throw new Error();setData(b);return true;}catch{setNotice('Could not refresh inventory. Review again before changing stock.');return false;}};
 useEffect(()=>{let saved;try{saved=sessionStorage.getItem('management:pending');if(saved)setPending(JSON.parse(saved));}catch{setNotice('Pending action could not be read. Stop and review before writing.');setBusy(true);}if(!initial)void load();},[]); // one load; actions explicitly refresh authoritative state
 async function send(command:Command):Promise<RowResult>{
  setPending(command);sessionStorage.setItem('management:pending',JSON.stringify(command));
  try{const r=await fetch('/api/management/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command),signal:AbortSignal.timeout(20000)});const body=await r.json();redirect(body);
   if(body.status==='uncertain'||(r.status>=500&&!body.status))throw new Error();
   sessionStorage.removeItem('management:pending');setPending(null);
   const result:RowResult={status:r.ok?'applied':body.status==='conflict'?'conflict':'failed',message:body.message};
   setNotice(r.ok?'Saved.':body.message??'Access changed. Sign in again.');return result;
  }catch{setNotice('Result unconfirmed. Retry the same action below before making another change.');return {status:'uncertain'};}
 }
 async function act(command:Command){if(lock.current||busy||(pending&&pending.key!==command.key))return;lock.current=true;setBusy(true);try{
  const result=await send(command);if(command.kind==='count')setResults(r=>({...r,[command.id]:result}));
  if(result.status==='applied'){setReceive(null);setPrepForm(null);}await load();
 }finally{lock.current=false;setBusy(false);}}
 async function submitCounts(){if(lock.current||busy||pending)return;lock.current=true;setBusy(true);try{
  for(const [id,c] of Object.entries(counts)){
   if(c.value===''||results[id]?.status==='applied'||results[id]?.status==='conflict'||results[id]?.status==='uncertain')continue;
   const result=await send({kind:'count',id,key:key(),quantity:c.value,unit:c.unit,revision:c.revision});setResults(r=>({...r,[id]:result}));if(result.status==='uncertain')break;
  }await load();
 }finally{lock.current=false;setBusy(false);}}
 const blocked=busy||pending!==null;
 const showCount=(item?:Inventory)=>{setSection('Inventory');setCountMode(true);if(item)setSearch(item.name);};
 const showReceive=(i:Inventory)=>{setReceive(i.id);setQty('');setUnit(i.displayUnit);setSection('Inventory');};
 const openPrep=(id:string,kind:'request'|'threshold',quantity:string)=>{setSection('Prep');setPrepForm({id,kind});setPrepQty(quantity);setNote('');};
 const moneylessStock=(i:Inventory)=>`${fmt(displayQuantity(i))} ${i.displayUnit}`;
 const attention=data?.inventory.filter(i=>['Low','Critical','Reconcile'].includes(i.status)||(i.quantity!==null&&i.quantity<=0))??[];
 const openRequests=data?.requests.filter(r=>r.state==='OPEN')??[];
 const filtered=data?filteredInventory(data.inventory,search,category,status).sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name)):[];
 const receiveItem=data?.inventory.find(i=>i.id===receive);
 return <div className={styles.shell}>
  <aside className={styles.sidebar}><p className="eyebrow">BarThings · Management</p><nav aria-label="Management sections">{(['Overview','Inventory','Prep','Recipes','Activity','Staff'] as Section[]).map(s=><button key={s} className={section===s?styles.selected:''} aria-current={section===s?'page':undefined} disabled={busy} onClick={()=>setSection(s)}>{s}</button>)}</nav>{signOut}</aside>
  <main className={styles.content}><header className={styles.header}><div><h1>{section}</h1><p>{section==='Overview'?'What needs attention today?':'Operational control'}</p></div><button className="secondary" disabled={blocked} onClick={()=>void load()}>Update view</button></header>
   <p role="status">{notice}</p>{pending&&<div className={styles.warning}>An action is awaiting confirmation. <button disabled={busy} onClick={()=>void act(pending)}>Retry same action</button></div>}
   {!data?<p>Loading Management…</p>:<>
    <section className={styles.quickSearch}><label>Find an item or recipe<input type="search" value={quickSearch} onChange={e=>setQuickSearch(e.target.value)} placeholder="Name or category…"/></label>{quickSearch.trim()&&<ul>{data.inventory.filter(i=>`${i.name} ${i.category}`.toLowerCase().includes(quickSearch.trim().toLowerCase())).map(i=><li key={i.id}><button className="secondary" onClick={()=>{setElement(i.id);setQuickSearch('');}}>{i.name} · {i.category}</button></li>)}{(data.menu??[]).filter(m=>m.name.toLowerCase().includes(quickSearch.trim().toLowerCase())).map(m=><li key={m.id}><button className="secondary" onClick={()=>{setElement(m.id);setQuickSearch('');}}>{m.name} · Menu item</button></li>)}{data.recipes.filter(r=>r.name.toLowerCase().includes(quickSearch.trim().toLowerCase())).map(r=><li key={r.id}><button className="secondary" onClick={()=>{setElement(r.id);setQuickSearch('');}}>{r.name} · Recipe</button></li>)}</ul>}</section>
    {element&&<section className={styles.recipe} aria-label="Element details"><button className="secondary" onClick={()=>setElement(null)}>Close details</button>{(()=>{const i=data.inventory.find(i=>i.id===element),r=data.recipes.find(r=>r.id===element);const menu=data.menu?.find(m=>m.id===element);return menu?<><h2>{menu.name}</h2><p>{menu.configured?'Published serving':'Serving not configured'}</p><ul>{menu.ingredients.map((i,n)=><li key={n}>{i.quantity} {i.unit} · {i.name}</li>)}</ul><p>Live serving availability and service details are not provided.</p></>:i?<><h2>{i.name}</h2><p>{i.category} · {moneylessStock(i)} · {i.status}</p><p>Low: {i.low??'Not configured'} · Critical: {i.critical??'Not configured'}{i.low!==null||i.critical!==null?` (${i.baseUnit})`:''}</p><h3>Used in</h3>{data.recipes.filter(r=>r.ingredients.some(x=>x.name===i.name)).map(r=><button key={r.id} className="secondary" onClick={()=>setElement(r.id)}>{r.name}</button>)}<p>Storage location not configured.</p></>:r?<><h2>{r.name}</h2><h3>Ingredients per batch</h3><ul>{r.ingredients.map((i,n)=><li key={n}>{i.quantity} {i.unit} · {i.name}</li>)}</ul><ol>{r.steps.map((s,n)=><li key={n}><strong>{s.name}</strong><p>{s.instructions}</p></li>)}</ol></>:null;})()}</section>}
    {section==='Overview' &&<>
     <dl className={styles.summary}><div><dt>Items needing attention</dt><dd>{attention.length}</dd></div><div><dt>Low Batch Stock</dt><dd>{data.prep.filter(p=>p.shouldPrep).length}</dd></div><div><dt>Open prep requests</dt><dd>{openRequests.length}</dd></div><div><dt>Negative theoretical balances</dt><dd>{data.inventory.filter(i=>i.status==='Reconcile').length}</dd></div></dl>
     <p>Last 24 hours: {data.activity?.length??0} inventory movements. <button className="secondary" onClick={()=>setSection('Activity')}>View activity</button></p><h2>Understock</h2>{attention.length===0?<p>No configured stock exceptions.</p>:<div className={styles.tableWrap}><table><thead><tr><th>Item</th><th>Theoretical stock</th><th>Status</th><th>Action</th></tr></thead><tbody>{attention.map(i=><tr key={i.id}><th>{i.name}</th><td>{moneylessStock(i)}</td><td>{i.status}</td><td>{i.category==='BATCH'?<button disabled={blocked||!i.recipeId||openRequests.some(r=>r.recipe_id===i.recipeId)} onClick={()=>openPrep(i.recipeId!,'request','1')}>Request prep</button>:<button disabled={blocked} onClick={()=>i.status==='Reconcile'?showCount(i):showReceive(i)}>{i.status==='Reconcile'?'Physical count':'Receive inventory'}</button>}</td></tr>)}</tbody></table></div>}
     <div className={styles.snapshots}><section><h2>Batch Stock</h2>{data.prep.map(p=><p key={p.id}>{p.name}: {fmt(p.stock)} batches{p.shouldPrep?' · Below threshold':''}</p>)}</section><section><h2>Inventory categories</h2>{[...categories,'BATCH'].map(c=><p key={c}>{c.replaceAll('_',' ')} · {data.inventory.filter(i=>i.category===c).length} items</p>)}</section><section><h2>Open prep requests</h2>{openRequests.length===0?<p>No open requests.</p>:openRequests.map(r=><p key={r.request_id}>{data.prep.find(p=>p.id===r.recipe_id)?.name??'Recipe'} · {r.remaining} batches remaining</p>)}<p>{data.countDiscrepancies} recorded count differences (history)</p></section></div>
    </>}
    {section==='Inventory'&&<>
     <div className={styles.filters}><label>Search inventory<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['All',...categories,'BATCH'].map(c=><option key={c}>{c}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{['All','Healthy','Low','Critical','Reconcile','Unconfigured','Count needed'].map(s=><option key={s}>{s}</option>)}</select></label><button disabled={blocked} onClick={()=>setCountMode(!countMode)}>{countMode?'Close count sheet':'Physical count'}</button></div>
     {receiveItem&&<form className={styles.actionForm} onSubmit={e=>{e.preventDefault();void act({kind:'receive',id:receiveItem.id,key:key(),quantity:qty,unit});}}><h2>Receive · {receiveItem.name}</h2><label>Quantity<input inputMode="decimal" required value={qty} disabled={blocked} onChange={e=>setQty(e.target.value)}/></label><label>Unit<select value={unit} disabled={blocked} onChange={e=>setUnit(e.target.value)}>{receiveItem.units.map(u=><option key={u.name}>{u.name}</option>)}</select></label><p>1 {unit} = {receiveItem.units.find(u=>u.name===unit)?.factor} {receiveItem.baseUnit}</p><button disabled={blocked}>Receive</button><button type="button" className="secondary" disabled={blocked} onClick={()=>setReceive(null)}>Cancel</button></form>}
     {countMode&&<p>Enter physical quantities. Each row is reconciled independently; applied rows will not be sent again.</p>}
     {!countMode&&[...categories,'BATCH'].filter(c=>filtered.some(i=>i.category===c)).map(c=><section key={c} className={styles.inventoryGroup} aria-label={c==='BATCH'?'Prepared Batch Stock':c.replaceAll('_',' ')}><header><h2>{c==='BATCH'?'Prepared Batch Stock':c==='OTHER'?'Other / unconfigured':c.replaceAll('_',' ')}</h2><small>{filtered.filter(i=>i.category===c).length} items</small></header><div className={styles.tableWrap}><table><thead><tr><th>Item</th><th>Theoretical stock</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.filter(i=>i.category===c).map(i=><tr key={i.id}><th><button className={styles.itemLink} onClick={()=>setElement(i.id)}>{i.name}</button></th><td>{moneylessStock(i)}{i.displayUnit!==i.baseUnit&&<small>1 {i.displayUnit} = {i.units.find(u=>u.name===i.displayUnit)?.factor} {i.baseUnit}</small>}</td><td>{i.status}</td><td><div className={styles.actions}>{i.itemId&&<button disabled={blocked||i.quantity===null} onClick={()=>showReceive(i)}>Receive</button>}<button className="secondary" disabled={blocked} onClick={()=>showCount(i)}>Count</button></div></td></tr>)}</tbody></table></div></section>)}
     {countMode&&<div className={styles.tableWrap}><table><thead><tr><th>Item</th><th>Category</th><th>Theoretical stock</th><th>Unit</th><th>Status</th>{countMode?<><th>Counted</th><th>Difference</th><th>Result</th></>:<th>Action</th>}</tr></thead><tbody>{filtered.flatMap((i,index)=>{const c=counts[i.id],u=c?.unit??i.displayUnit,factor=Number(i.units.find(x=>x.name===u)?.factor??1),theoretical=i.quantity===null?null:i.quantity/factor,res=results[i.id];return [index===0||filtered[index-1].category!==i.category?<tr key={`group-${i.category}-${index}`}><th colSpan={countMode?8:6}>{i.category==='BATCH'?'Prepared Batch Stock':i.category.replaceAll('_',' ')}</th></tr>:null,<tr key={i.id}><th>{i.name}</th><td>{i.category.replaceAll('_',' ')}</td><td>{fmt(countMode?theoretical:displayQuantity(i))}</td><td>{countMode?<select aria-label={`Count unit ${i.name}`} disabled={blocked||!!res} value={u} onChange={e=>setCounts(v=>({...v,[i.id]:{value:'',unit:e.target.value,revision:i.revision}}))}>{i.units.map(u=><option key={u.name}>{u.name}</option>)}</select>:<>{i.displayUnit}{i.displayUnit!==i.baseUnit&&<small>1 {i.displayUnit} = {i.units.find(u=>u.name===i.displayUnit)?.factor} {i.baseUnit}</small>}</>}</td><td>{i.status}</td>{countMode?<><td><input aria-label={`Count ${i.name}`} inputMode="decimal" disabled={blocked||res?.status==='applied'||res?.status==='conflict'||res?.status==='uncertain'} value={c?.value??''} onChange={e=>setCounts(v=>({...v,[i.id]:{value:e.target.value,unit:u,revision:c?.revision??i.revision}}))}/></td><td>{c?.value&&Number.isFinite(Number(c.value))&&theoretical!==null?fmt(Number(c.value)-theoretical):'—'}</td><td>{res?.status??'Not submitted'}{res?.status==='conflict'&&<button disabled={blocked} onClick={async()=>{if(await load()){setCounts(v=>{const next={...v};delete next[i.id];return next;});setResults(v=>{const next={...v};delete next[i.id];return next;});}}}>Review and re-enter</button>}{res?.message&&<small>{res.message}</small>}</td></>:<td><div className={styles.actions}>{i.itemId&&<button disabled={blocked||i.quantity===null} onClick={()=>showReceive(i)}>Receive</button>}<button className="secondary" disabled={blocked} onClick={()=>showCount(i)}>Count</button></div></td>}</tr>];})}</tbody></table></div>}
     {filtered.length===0&&<p>No matching inventory.</p>}{countMode&&<button disabled={blocked||!Object.values(counts).some(c=>c.value!=='')} onClick={()=>void submitCounts()}>Reconcile entered counts</button>}
    </>}
    {section==='Prep'&&<>
     {prepForm&&<form className={styles.actionForm} onSubmit={e=>{e.preventDefault();void act({kind:prepForm.kind,id:prepForm.id,key:key(),quantity:prepQty,...(prepForm.kind==='request'?{note}:{})});}}><h2>{prepForm.kind==='request'?'Request prep':'Set prep threshold'} · {data.prep.find(p=>p.id===prepForm.id)?.name}</h2><label>Standardized batches<input required inputMode="decimal" value={prepQty} disabled={blocked} onChange={e=>setPrepQty(e.target.value)}/></label>{prepForm.kind==='request'&&<label>Note (optional)<input value={note} maxLength={2000} disabled={blocked} onChange={e=>setNote(e.target.value)}/></label>}<button disabled={blocked}>Save</button><button type="button" className="secondary" disabled={blocked} onClick={()=>setPrepForm(null)}>Cancel</button></form>}
     <div className={styles.tableWrap}><table><thead><tr><th>Batch</th><th>Stock</th><th>Threshold</th><th>Status</th><th>Open request</th><th>Action</th></tr></thead><tbody>{data.prep.map(p=>{const r=openRequests.find(r=>r.recipe_id===p.id);return <tr key={p.id}><th>{p.name}</th><td>{fmt(p.stock)} batches</td><td>{fmt(p.threshold)}</td><td>{p.stock===null?'Count needed':p.shouldPrep?'Suggested':'Above threshold'}</td><td>{r?`${r.remaining} remaining`:'None'}</td><td><div className={styles.actions}><button disabled={blocked||!!r} onClick={()=>openPrep(p.id,'request','1')}>Request prep</button><button className="secondary" disabled={blocked} onClick={()=>openPrep(p.id,'threshold',String(p.threshold))}>Edit threshold</button></div></td></tr>;})}</tbody></table></div>
     <h2>Prep requests</h2><div className={styles.tableWrap}><table><thead><tr><th>Recipe</th><th>Requested</th><th>Fulfilled</th><th>In progress</th><th>Remaining</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.requests.map(r=><tr key={r.request_id}><th>{data.prep.find(p=>p.id===r.recipe_id)?.name??'Historical recipe'}</th><td>{r.requested}</td><td>{r.fulfilled}</td><td>{r.in_progress}</td><td>{r.remaining}</td><td>{r.state}</td><td>{r.state==='OPEN'&&<button disabled={blocked} className="secondary" onClick={()=>{if(window.confirm('Cancel this request? Existing production is preserved.'))void act({kind:'cancel',id:r.request_id,key:key()});}}>Cancel request</button>}</td></tr>)}</tbody></table></div>
    </>}
    {section==='Recipes'&&<><p>Published recipes · read-only</p>{data.recipes.map(r=><details className={styles.recipe} key={r.id}><summary>{r.name} · {r.mode} · Version {r.version}</summary><p>Batch increment: {r.increment}</p><h3>Ingredients per batch</h3><ul>{r.ingredients.map((i,n)=><li key={n}>{i.name} · {i.quantity} {i.unit}{i.step?` · ${i.step}`:''}</li>)}</ul><h3>Steps</h3><ol>{r.steps.map((s,n)=><li key={n}><strong>{s.name}</strong><p>{s.instructions}</p></li>)}</ol></details>)}</>}
    {section==='Activity'&&<section><h2>Last 24 hours</h2><p>{data.activity?.length??0} inventory movements · current stock is the latest snapshot, not the balance at event time.</p>{(data.activity??[]).map(m=><article key={m.id} className={styles.recipe}><time dateTime={m.time}>{new Date(m.time).toLocaleString()}</time><h3>{m.kind.toLowerCase().replaceAll('_',' ')}</h3><ul>{m.lines.map((l,n)=><li key={n}>{l.name}: {l.delta>0?'+':''}{fmt(l.delta)} {l.unit} · now {fmt(l.current)} {l.unit}</li>)}</ul></article>)}</section>}
    {section==='Staff' &&<><p>Existing profiles only. At least one active management profile must remain.</p><div className={styles.tableWrap}><table><thead><tr><th>Staff member</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.staff.map(s=><tr key={s.id}><th>{s.display_name}{s.id===staffId?' (you)':''}</th><td>{s.role}</td><td>{s.active?'Active':'Inactive'}</td><td><div className={styles.actions}><button disabled={blocked} onClick={()=>{if(window.confirm(`${s.active?'Deactivate':'Activate'} ${s.display_name}?`))void act({kind:'staff',id:s.id,key:key(),active:!s.active});}}>{s.active?'Deactivate':'Activate'}</button><button disabled={blocked} className="secondary" onClick={()=>{if(window.confirm(`Change ${s.display_name} to ${s.role==='management'?'bartender':'management'}?`))void act({kind:'staff',id:s.id,key:key(),role:s.role==='management'?'bartender':'management'});}}>Make {s.role==='management'?'bartender':'management'}</button></div></td></tr>)}</tbody></table></div></>}
   </>}
   <div className={styles.demo}>{demo}</div>
  </main>
 </div>;
}
